create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  pet_type text not null,
  pet_size text not null,
  service_package text not null,
  appointment_date date not null,
  appointment_time text not null,
  note text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint appointments_customer_name_check check (length(trim(customer_name)) between 1 and 50),
  constraint appointments_customer_phone_check check (customer_phone ~ '^1[3-9][0-9]{9}$'),
  constraint appointments_pet_type_check check (pet_type in ('猫咪', '狗狗', '其他小宠')),
  constraint appointments_pet_size_check check (pet_size in ('小型', '中型', '大型')),
  constraint appointments_service_package_check check (service_package in ('轻盈洗护', '泡泡精护', '明星造型')),
  constraint appointments_status_check check (status in ('pending', 'confirmed', 'cancelled', 'completed'))
);

alter table public.appointments enable row level security;

create index if not exists appointments_appointment_date_idx
  on public.appointments (appointment_date, appointment_time);

create or replace function public.set_appointments_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists appointments_set_updated_at on public.appointments;

create trigger appointments_set_updated_at
before update on public.appointments
for each row
execute function public.set_appointments_updated_at();
